"""Write flow/inventory/stock-assets-api.md: every whitelisted method in ERPNext's stock and
assets modules, and where briskrew uses it.

  python flow/scripts/stock-assets-api-map.py ~/frappe-bench/apps

A method is "desk script" when ERPNext's (or Frappe's, or Frappe HR's) own desk JavaScript calls it:
briskrew runs those scripts unchanged on its forms and lists, so the method is reached exactly as
in the desk. "briskrew screen" means one of briskrew's own designed screens calls it. "Server /
API only" means no desk script calls it: other server code, integrations or the REST API do.
"""

import ast
import os
import re
import sys
from collections import Counter

APPS = os.path.expanduser(sys.argv[1] if len(sys.argv) > 1 else "~/frappe-bench/apps")
ERPNEXT = os.path.join(APPS, "erpnext", "erpnext")
REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(REPO, "flow", "inventory", "stock-assets-api.md")
WORD = re.compile(r"[A-Za-z_][A-Za-z0-9_.]*")


def words(roots, exts, pages=None):
	"""Identifiers in these files. pages=True: only desk pages' files; False: all but them."""
	found, text = set(), []
	for root in roots:
		for dirpath, dirnames, files in os.walk(root):
			dirnames[:] = [d for d in dirnames if d not in ("node_modules", "dist", ".git")]
			in_page = f"{os.sep}page{os.sep}" in dirpath + os.sep
			if pages is not None and in_page != pages:
				continue
			for f in files:
				if f.endswith(exts):
					with open(os.path.join(dirpath, f), errors="ignore") as fh:
						content = fh.read()
					text.append(content)
					found.update(WORD.findall(content))
	return found, "\n".join(text)


def whitelisted(module):
	out = []
	for dirpath, _, files in os.walk(os.path.join(ERPNEXT, module)):
		for f in files:
			if not f.endswith(".py") or f.startswith("test_"):
				continue
			path = os.path.join(dirpath, f)
			try:
				tree = ast.parse(open(path).read())
			except SyntaxError:
				continue
			dotted = "erpnext." + os.path.relpath(path, ERPNEXT)[:-3].replace(os.sep, ".")

			def walk(nodes, cls=None):
				for n in nodes:
					if isinstance(n, ast.ClassDef):
						walk(n.body, n.name)
					elif isinstance(n, ast.FunctionDef | ast.AsyncFunctionDef):
						if any("whitelist" in ast.unparse(d) for d in n.decorator_list):
							out.append((dotted, cls, n.name))

			walk(tree.body)
	return sorted(out, key=lambda m: (m[0], m[1] or "", m[2]))


desk_words, _ = words([ERPNEXT, os.path.join(REPO, "hrms")], (".js",), pages=False)
page_words, _ = words([ERPNEXT, os.path.join(REPO, "hrms")], (".js",), pages=True)
flow_words, flow_text = words(
	[os.path.join(REPO, "flow", "src"), os.path.join(REPO, "hrms", "briskrew")], (".js", ".vue", ".py")
)

sections, totals = [], Counter()
for module, title in (("stock", "Stock"), ("assets", "Assets")):
	rows = []
	for dotted, cls, name in whitelisted(module):
		if cls:
			label = f"`{cls}.{name}` (document method)"
			flow_use = False
			desk_use = name in desk_words
			page_use = False
		else:
			full = f"{dotted}.{name}"
			label = f"`{full}`"
			flow_use = full in flow_words or (name in flow_words and dotted in flow_text)
			desk_use = full in desk_words
			page_use = full in page_words
		where = (
			"briskrew screen"
			if flow_use
			else "desk script"
			if desk_use
			else "classic desk page"
			if page_use
			else "server / API only"
		)
		totals[(title, where)] += 1
		rows.append(f"| {label} | {where} |")
	sections.append(f"## {title}\n\n| Method | Used by |\n|---|---|\n" + "\n".join(rows))

summary = "\n".join(
	f"| {m} | {totals[(m, 'desk script')]} | {totals[(m, 'briskrew screen')]} | "
	f"{totals[(m, 'classic desk page')]} | {totals[(m, 'server / API only')]} |"
	for m in ("Stock", "Assets")
)
with open(OUT, "w") as fh:
	fh.write(
		f"""# Stock and assets: API coverage

Every whitelisted method in ERPNext's `stock` and `assets` modules, and where briskrew uses it.
Generated by `flow/scripts/stock-assets-api-map.py`; re-run it after an upstream sync.

- **desk script**: ERPNext's own form, list or report scripts call it. briskrew runs those
  scripts unchanged (`flow/src/engine/compat.js`), so the method is used exactly as in the desk.
  The screen audit (`flow/scripts/audit-priority-screens.cjs stock` and `assets`) checks those
  scripts run without errors.
- **briskrew screen**: one of briskrew's designed screens (Stock levels, item page, Asset
  register, asset page) calls it, through `hrms/briskrew/inventory.py`.
- **classic desk page**: only one of the desk's own pages (not a form, list or report) calls
  it. briskrew doesn't run desk pages; open them from the classic desk (the Stock levels screen
  covers the desk's Stock Summary page).
- **server / API only**: no desk script calls it. Other server code, integrations or the REST
  API use it, and it works the same with briskrew installed.

| Module | Desk script | briskrew screen | Classic desk page | Server / API only |
|---|---|---|---|---|
{summary}

{chr(10).join(s + chr(10) for s in sections)}"""
	)
print(f"wrote {OUT}")
